### ISSUE TITLE
Planning and Documentation

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/to-do-app#1]
## Description:

**In order to** provide a comprehensive project plan and documentation for our developing period, **as a** project manager, **I can** create a detailed planning document and readme description.

## Acceptance Criteria:

- **Acceptance Criteria 1:** Create a readme file and provide a brief project description.
- **Acceptance Criteria 2:** Include setup instructions, documenting the project's features and usage with all UX/UI thinking.
- **Acceptance Criteria 3:** Allocate tasks to the development team members and set a clear sprint duration and start date.

## Tasks:

- [x] Plan Sprint
- [x] Create and write readme file
- [x] Design Database Schema
- [x] Create the wireframes
