### ISSUE TITLE
USER STORY: Delete a Task

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/to-do-app#11]
---

## EPIC: **#4**

**In order to** remove unnecessary tasks, **as a** logged-in user, **I want to** permanently delete an existing task.

## Acceptance Criteria:

- **Acceptance Criteria 1:** User has already created a task.
- **Acceptance Criteria 2:** User can locate the task and click a Delete button.
- **Acceptance Criteria 3:** Task is permanently removed from every list.

## Tasks:

- [x] Implement button for deleting a task
- [x] Backend: Implement API endpoint for deleting a task
- [x] Ensure task is permanently deleted from database upon deletion
