### ISSUE TITLE
USER STORY: Mark a Task as Complete

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/to-do-app#12]
---

## EPIC: **#4**

**In order to** track completed tasks, **as a** logged-in user, **I want to** mark a task as complete and have it moved to the completed section.

## Acceptance Criteria:

- **Acceptance Criteria 1:** User has already created a task.
- **Acceptance Criteria 2:** User can locate the task and click a Done button.
- **Acceptance Criteria 3:** Task is immediately moved to the completed section.

## Tasks:

- [x] Implement button for marking a task as complete
- [x] Backend: Implement API endpoint for marking a task as complete
- [ ] Ensure task is dynamically moved to the completed section upon marking as complete

**Comment by KimBergstroem** [comment]
Marking task items as complete and reflecting them in the Supabase database is DONE. The only thing remaining for this task is that I have not created a complete section where completed tasks can be stored or viewed by the user.
